### ISSUE TITLE
Create recipe for 75% chapter that is available in cnxml

### ISSUE THREAD

**Issue by openstaxalina** [openstax/mathify#29]
@brittweinstein commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/77)

---

@staxly[bot] commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/77#issuecomment-407522724)

The maintainers of this repository would appreciate it if you could provide more information.

**Comment by brittweinstein** [comment]
Not a lot of info and not quite sure what this is. I don't think we need this anymore, but we can open again if we need it.
