### ISSUE TITLE
Push 75% chapter through BakedPDF as prototype

### ISSUE THREAD

**Issue by openstaxalina** [openstax/mathify#30]
@brittweinstein commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/78)

---

@staxly[bot] commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/78#issuecomment-407522885)

The maintainers of this repository would appreciate it if you could provide more information.

**Comment by brittweinstein** [comment]
Not a lot of info and not quite sure what this is. I don't think we need this anymore, but we can open again if we need it.
